### PR TITLE
fix(syndicates): switch to Fandom MediaWiki API for fetching

### LINKED ISSUE #94: [bug] Syndicate scraper blocked by Cloudflare, resulting in empty syndicate data
### Syndicate scraper blocked by Cloudflare, resulting in empty syndicate data
---

The syndicate scraper in lib/syndicates.js fetches wiki pages directly, but these requests are now blocked by Cloudflare's bot protection, returning a JavaScript challenge page instead of actual  content. As a result, all syndicate arrays in data/syndicates.json are empty.

---
**Reproduction:**
  1. Clone the repository
  2. Run node generateData.js (or the syndicate scraper directly)
  3. Open data/syndicates.json                                   
  4. See all syndicate arrays are empty ([]) 

---
**Mockups, screenshots, evidence:**

The scraper receives this instead of the wiki page: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>  ...Enable JavaScript and cookies to continue...    

---

**Additional context**
The Fandom MediaWiki API endpoint doesn't seem to be affected by this Cloudflare block and returns the same content.
Example URL: [https://warframe.fandom.com/api.php?action=parse&page=Steel_Meridian&prop=text&format=json](https://warframe.fandom.com/api.php?action=parse&page=Steel_Meridian&prop=text&format=json)
The HTML is available at response.parse.text["*"] and shoud be possible to feed it directly into cheerio with no other changes to the parsing logic needed.

### PR DESCRIPTION
**Pull request by gjrud**
### Warframe Drop Data Site Pull Request

---

**What I did:**
Switched the syndicate scraper in `lib/syndicates.js` from fetching wiki pages directly to using the Fandom MediaWiki API (`/api.php?action=parse&page=...&prop=text&format=json`). 
The parsed HTML is extracted from the JSON response and fed into the existing parsing logic unchanged.

---

**Why I did it:**
Cloudflare bot protection started blocking direct page requests, returning a JS challenge page instead of wiki content, leaving all syndicate arrays empty.

---

**Fixes issue (include link):**
Fixes #94 - syndicate scraper blocked by Cloudflare, resulting in empty syndicate data.

---

**Mockups, screenshots, evidence:**
`data/syndicates.json` now populated after switching to the API endpoint.

---

**Was this an issue fix or a suggestion fulfillment?**
Issue fix.

## Summary by CodeRabbit

* **Chores**
  * Updated internal metadata timestamp.
* **Improvements**
  * Improved syndicate data sourcing to use Fandom wiki pages with a more robust fallback when external fetches fail.

### CODE REVIEW

File: lib/syndicates.js [hunk 1]
```diff
@@ -327,7 +327,8 @@ export default async () => {
       let data;
       try {
         // Fetch page for this syndicate.
-        data = await fetch(syndicate.url).then((res) => res.text());
+        const apiUrl = `https://warframe.fandom.com/api.php?action=parse&page=${syndicate.fandomWikiPage}&prop=text&format=json`;
```
Comment (TobiTenno) [inline lib/syndicates.js]: seems like this should switch from `warframe.fandom.com` to `wiki.warframe.com` if we're making this change anyway. 

```suggestion
        const apiUrl = `https://wiki.warframe.com/api.php?action=parse&page=${syndicate.fandomWikiPage}&prop=text&format=json`;
```

**Review by TobiTenno — CHANGES_REQUESTED** [review]

File: lib/syndicates.js [hunk 2]
```diff
@@ -327,7 +327,8 @@ export default async () => {
       let data;
       try {
         // Fetch page for this syndicate.
-        data = await fetch(syndicate.url).then((res) => res.text());
+        const apiUrl = `https://wiki.warframe.com/api.php?action=parse&page=${syndicate.fandomWikiPage}&prop=text&format=json`;
+        data = await fetch(apiUrl).then((res) => res.json()).then((json) => json.parse.text['*']);
```
Comment (TobiTenno) [inline lib/syndicates.js]:
```suggestion
        data = await fetch(apiUrl)
          .then((res) => res.json())
          .then((json) => json.parse.text['*']);
```

**Review by TobiTenno — APPROVED** [review]

**Comment by TobiTenno** [comment]
thanks bunches, @gjrud!
